//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.29 at 09:47:49 PM EET 
//


package com.shaheen.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.shaheen.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GathererProfile_QNAME = new QName("", "GathererProfile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.shaheen.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GathererProfileType }
     * 
     */
    public GathererProfileType createGathererProfileType() {
        return new GathererProfileType();
    }

    /**
     * Create an instance of {@link Vectors3Type }
     * 
     */
    public Vectors3Type createVectors3Type() {
        return new Vectors3Type();
    }

    /**
     * Create an instance of {@link PositionType }
     * 
     */
    public PositionType createPositionType() {
        return new PositionType();
    }

    /**
     * Create an instance of {@link GathererBlackListRadiusType }
     * 
     */
    public GathererBlackListRadiusType createGathererBlackListRadiusType() {
        return new GathererBlackListRadiusType();
    }

    /**
     * Create an instance of {@link Vector3Type }
     * 
     */
    public Vector3Type createVector3Type() {
        return new Vector3Type();
    }

    /**
     * Create an instance of {@link BlackListRadiusType }
     * 
     */
    public BlackListRadiusType createBlackListRadiusType() {
        return new BlackListRadiusType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GathererProfileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GathererProfile")
    public JAXBElement<GathererProfileType> createGathererProfile(GathererProfileType value) {
        return new JAXBElement<GathererProfileType>(_GathererProfile_QNAME, GathererProfileType.class, null, value);
    }

}
